platform: linux

image_resource:
  type: registry-image
  source:
    repository: ruby
    tag: 2.7.1
    username: ((LicenseFinderDocker.username))
    password: ((LicenseFinderDocker.password))

inputs:
- name: LicenseFinder

run:
  path: ./LicenseFinder/ci/scripts/run-rubocop.sh